### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/flower#1]
**tasks**:
- [x]  sort by name/state/received/started
- [ ]  add worker column
- [x]   filter by received/started time
